# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a9aa32ff2513d98ef00cbad64ee752e3f6d781a4d2e9f30cd0211fe3360db4be8937d6643c15f3d92fbcc47a51abb247b8e28414b1f3787f8831b11dfbb24c7

test:
  secret_key_base: f2686faa8f337d93ec21f176c192549931c58b2cf71714e3a781e32f085280851c6b3a45470fee8d83530f0e090b1ecab7c998210a8d0788fd0f2e9fb2f0f109

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
